steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
        'build',
        '-t',
        '$PROJECT_ID/gencan-luna-wattch/luna_watch:$SHORT_SHA',
        '.'
        ]
images: 
  - '$PROJECT_ID/gencan-luna-wattch/luna_watch:$SHORT_SHA'
options:
  logging: 'CLOUD_LOGGING_ONLY'
