steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gencan-luna-watch/luna_watch', '.' ]
images: 
  - 'gencan-luna-watch/luna_watch:$SHORT_SHA'
  - 'gencan-luna-watch/luna_watch::latest'
options:
  logging: 'CLOUD_LOGGING_ONLY'
