steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
        'build',
        '-t',
        'us-central1.docker.pkg.dev/$PROJECT_ID/gencan-luna-wattch/luna_watch:$SHORT_SHA',
        '.'
        ]
images: 
  - 'us-central1.docker.pkg.dev/$PROJECT_ID//gencan-luna-wattch/luna_watch:$SHORT_SHA'
options:
  logging: 'CLOUD_LOGGING_ONLY'
