steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
        'build',
        '-t',
        'gcr.io/gencan-luna-wattch/luna_watch:$SHORT_SHA',
        '.'
        ]
images: 
  - 'gcr.io/gencan-luna-wattch/luna_watch:$SHORT_SHA'
options:
  logging: 'CLOUD_LOGGING_ONLY'
