# Generated by Django 5.0.6 on 2024-07-30 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(verbose_name='First day of the watch')),
                ('end_date', models.DateField(verbose_name='Last day of the watch')),
                ('pet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_luna_watch.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Date of this visit')),
                ('visit_time', models.TimeField(verbose_name='Time of the visit')),
                ('needs_feeding', models.BooleanField(default=True, verbose_name='Serve food?')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_luna_watch.schedule')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_luna_watch.visitor')),
            ],
        ),
    ]
