# Generated by Django 5.0.6 on 2024-08-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_luna_watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='pet_name',
            new_name='pet',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_name',
        ),
    ]
