# Generated by Django 5.0.6 on 2024-08-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_luna_watch', '0003_schedule_visits_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='visit_times',
            field=models.CharField(default='07:00 AM, 12:00 PM, 5:00 PM', max_length=64),
        ),
    ]
