# Generated by Django 5.0.6 on 2024-08-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_luna_watch', '0004_schedule_visit_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='scheduled',
            field=models.BooleanField(default=False, verbose_name='Visit Scheduled'),
        ),
    ]
