# Generated by Django 5.0.6 on 2024-08-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_luna_watch', '0005_visit_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_time',
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_datetime',
            field=models.DateTimeField(null=True, verbose_name='Date and Time of the visit'),
        ),
    ]
