# Generated by Django 5.0.6 on 2024-08-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_luna_watch', '0006_remove_visit_visit_date_remove_visit_visit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='scheduled',
            field=models.BooleanField(default=True, verbose_name='Visit Scheduled'),
        ),
    ]
