# Generated by Django 5.0.6 on 2024-08-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_luna_watch', '0007_alter_visit_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='scheduled',
        ),
    ]
